openapi: 3.0.3

info:
  title: Weather Shield Gateway API
  description: |
    A sample Weather API used to demonstrate Google Cloud Apigee concepts,
    including API proxy development, security, mediation, caching,
    quota management, and response transformation.

    This specification is intended for learning and portfolio purposes.
  version: 1.0.0
  contact:
    name: Sunny JayaRaju
    url: https://github.com/SunnyJayaRaju
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/v1
    description: Mock Backend

tags:
  - name: Weather
    description: Weather operations

security:
  - ApiKeyAuth: []

paths:
  /weather:
    get:
      tags:
        - Weather
      summary: Get current weather
      description: Returns the current weather conditions for the requested city.
      operationId: getCurrentWeather

      parameters:
        - name: city
          in: query
          description: Name of the city.
          required: true
          schema:
            type: string
            example: London

      responses:
        "200":
          description: Weather information retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WeatherResponse"

        "400":
          description: Invalid request.

        "401":
          description: Authentication failed.

        "429":
          description: Quota exceeded or Spike Arrest triggered.

        "500":
          description: Internal server error.

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  schemas:
    WeatherResponse:
      type: object
      required:
        - temperature
        - condition

      properties:
        temperature:
          type: integer
          description: Current temperature in Celsius.
          example: 28

        condition:
          type: string
          description: Current weather condition.
          example: Sunny