openapi: 3.0.3

info:
  title: Retail Mesh Orchestrator API
  description: |
    A sample API demonstrating service orchestration using Google Cloud
    Apigee. The proxy aggregates responses from multiple backend services
    into a single client response.

    This specification is intended for learning and portfolio purposes.
  version: 1.0.0
  contact:
    name: Sunny JayaRaju
    url: https://github.com/SunnyJayaRaju
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.retail-lab.com/v1
    description: Mock Backend
paths:
  /product/{productId}:
    get:
      summary: Get Product Composite Data
      description: Returns merged data (Item + Inventory) in a single call.
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            example: "555"
      responses:
        '200':
          description: Successful Merge
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "555"
                  name:
                    type: string
                    example: "Super Widget"
                  stock_level:
                    type: integer
                    example: 120
                  location:
                    type: string
                    example: "Warehouse-A"
